### ISSUE TITLE
parse_influenza_blast_results.py has two question

### ISSUE THREAD

**Issue by chendongo** [peterk87/nf-flu#19]
### Research

- [X] I have searched the documentation and previously asked questions.

### Question about nf-flu

you parse_influenza_blast_results.py has two question 
1: count not is counts
![image](https://github.com/peterk87/nf-flu/assets/33278480/cb9c0265-1d5b-4402-86d5-4f128f550147)
2: update not |=
![image](https://github.com/peterk87/nf-flu/assets/33278480/36007900-88d0-4ae3-9aee-cddd8361a649)

**Comment by peterk87** [comment]
Hi @chendongo I'm not sure what version or commit you're looking at, but the official repo for nf-flu is at https://github.com/CFIA-NCFAD/nf-flu

1. `|=` was added in Python 3.9 via [PEP 584](https://peps.python.org/pep-0584/) for updating dicts as an alternative to the `.update` method.
    > Update a dict in place: The Obvious Way is to use the update() method. If this proposal is accepted, the |= augmented assignment operator will also work, but that is a side-effect of how augmented assignments are defined. Which you choose is a matter of taste.
3. If this was an issue, it has been fixed since (https://github.com/CFIA-NCFAD/nf-flu/blob/db8f3e7fdbc55dc823b305bd06e57014195ab3d5/bin/parse_influenza_blast_results.py#L344).
